// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-frame-fields.mjs from schema/tclk1-frames.schema.json.
// Do not edit by hand.

export const FRAME_FIELDS = {
  "offer": {
    "allowed": [
      "type",
      "from",
      "role",
      "amount",
      "asset",
      "lock",
      "rails",
      "claimByMs",
      "refundAfterMs",
      "expiresMs",
      "paymentKey",
      "job",
      "nonce",
      "id"
    ],
    "required": [
      "type",
      "from",
      "role",
      "amount",
      "asset",
      "lock",
      "rails",
      "claimByMs",
      "refundAfterMs",
      "expiresMs",
      "nonce",
      "id"
    ]
  },
  "accept": {
    "allowed": [
      "type",
      "from",
      "ref",
      "statement",
      "contract",
      "paymentKey",
      "nonce"
    ],
    "required": [
      "type",
      "from",
      "ref",
      "statement",
      "contract",
      "nonce"
    ]
  },
  "lock": {
    "allowed": [
      "type",
      "from",
      "contract",
      "rail",
      "ref",
      "presig"
    ],
    "required": [
      "type",
      "from",
      "contract",
      "rail",
      "ref"
    ]
  },
  "reveal": {
    "allowed": [
      "type",
      "from",
      "contract",
      "ref",
      "secret"
    ],
    "required": [
      "type",
      "from",
      "contract",
      "ref",
      "secret"
    ]
  },
  "refund": {
    "allowed": [
      "type",
      "from",
      "contract",
      "ref",
      "reason"
    ],
    "required": [
      "type",
      "from",
      "contract",
      "ref"
    ]
  },
  "cancel": {
    "allowed": [
      "type",
      "from",
      "contract",
      "reason"
    ],
    "required": [
      "type",
      "from",
      "contract"
    ]
  },
  "receipt": {
    "allowed": [
      "type",
      "from",
      "contract",
      "outcome",
      "rail",
      "ref"
    ],
    "required": [
      "type",
      "from",
      "contract",
      "outcome"
    ]
  },
  "heartbeat": {
    "allowed": [
      "type",
      "from",
      "contract",
      "nonce",
      "note"
    ],
    "required": [
      "type",
      "from",
      "contract",
      "nonce"
    ]
  }
} as const;

export const CANONICAL_RAIL_IDS = [
  "btc-htlc",
  "evm-htlc",
  "flop-htlc",
  "memory",
  "near-htlc",
  "paper",
  "x402"
] as const;
